route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'business-alert'

receivers:
    - name: 'business-alert'
      webhook_configs:
          - send_resolved: false
            url: 'INCOMING_WEBHOOK'
